import Navbar from "@/components/Navbar";
import "./globals.css";
import Hero from "@/components/Hero";
import Features from "@/components/Features";
import CardsContent from "@/components/CardsContent";
import Products from "@/components/Products";
import Courses from "@/components/Courses";
import Offerings from "@/components/Offerings";
import Support from "@/components/Support";
import Newsletter from "@/components/Newsletter";
import Footer from "@/components/Footer";

export const metadata = {
  title: "My Next App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
     
      {/* Font Awesome CDN */}
      
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
          integrity="sha512-DxV+EoADOkOygM4IR9yXP8Sb2qwgidEmeqAEmDKIOfPRQZOWbXCzLC6vjbZyy0vPisbH2SyW27+ddLVCN+OMzQ=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
         {/* Google Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
          rel="stylesheet"
        />
        
      <body >
         <Navbar />
      <Hero />
      <Features />
      <CardsContent />
      <Products />
      <Courses />
      <Offerings />
      <Support />
      <Newsletter />
      <Footer />
        {children}</body>
    </html>
  );
}
